---
name: allow_audit_event_type_filtering
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/102502
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/373833
milestone: '15.6'
type: development
group: group::compliance
default_enabled: false
