---
name: ci_retry_job_fix
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/100712
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/207988
milestone: '15.6'
type: development
group: group::pipeline execution
default_enabled: false
