---
name: pipeline_name
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/97502
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/376095
milestone: '15.5'
type: development
group: group::delivery
default_enabled: false
