---
name: require_approval_on_scan_removal
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/102631
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/382079
milestone: '15.6'
type: development
group: group::security policies
default_enabled: false
