---
name: root_statistics_worker_read_replica
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/102516
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/379678
milestone: '15.6'
type: development
group: group::utilization
default_enabled: false
