---
key_path: usage_activity_by_stage_monthly.create.merge_request_authors_monthly
description: Number of unique merge request authors
product_section: dev
product_stage: create
product_group: code_review
product_category: code_review
value_type: number
status: active
milestone: "15.6"
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/103334
time_frame: 28d
data_source: database
data_category: optional
instrumentation_class: CountMergeRequestAuthorsMetric
distribution:
- ce
- ee
tier:
- free
- premium
- ultimate
